### ISSUE TITLE
Zig

### ISSUE THREAD

**Issue by SeekingMeaning** [Tearff/Minote#1]
Have you considered using the [Zig programming language](https://ziglang.org/)?

**Comment by Tearnote** [comment]
Hello, and thanks for the interest in the project. I was not aware of this language but from an initial look it seems quite promising, my only concerns would be with maturity and availability of build tools, as well as long term prospects.

If I was starting a completely new project I would most likely go with Rust (or now Zig). Minote however already went through a number of rewrites in different languages as I slowly became a less bad programmer, and at this point I'm tired of starting over and just want to get things done. I still don't consider it to be quality code (static vars everywhere...) but I believe I can see it through to the end this time.

The decision to go with C also isn't motivated by it being a particularly good language - my brain just seems to be incompatible with OOP at large and I'm quite intimately familiar with C's various warts and quirks, so it's the only language where I can immediately focus on solving the actual problems. I tried, and I couldn't just switch to something else without some practice projects to get more familiar with the new concepts and paradigms.

Thanks again for the issue - I learned something new today 🙌
